### ISSUE TITLE
mvc5 not working

### ISSUE THREAD

**Issue by x-light-ai** [tparnell8/CompressR#7]
I run CompressR.Sample(release),but it not working,why?
![1](https://cloud.githubusercontent.com/assets/17698581/20613172/461cd74c-b2fc-11e6-82ca-e02f46f17f51.png)
![2](https://cloud.githubusercontent.com/assets/17698581/20613173/49a7d06a-b2fc-11e6-9852-16b08b54ea42.png)

**Comment by TerribleDev** [comment]
The sample works fine for me. Are you sure you are sending gzip in the Accept-Encoding header on the request that is being sent to the server?

![image](https://cloud.githubusercontent.com/assets/3459800/20613240/f8cc0402-b28f-11e6-877e-cf1477b1358e.png)

**Comment by x-light-ai** [comment]
I think is sending,you can see:
![3](https://cloud.githubusercontent.com/assets/17698581/20613331/f0963474-b2fd-11e6-9ba6-cd89dff37796.png)

**Comment by TerribleDev** [comment]
Maybe add this inside system.webServer 

`<urlCompression doDynamicCompression="false" dynamicCompressionBeforeCache="false" doStaticCompression="false"/>`

maybe IIS is doing something funky?

**Comment by x-light-ai** [comment]
sorry,try it agagin,but  it seems no effect
===
os ver:10.0.14393
vs ver:vs2015 update3
iis express

**Comment by TerribleDev** [comment]
I can't seem to reproduce the behavior you are seeing. I'd look to see if you are running fiddler, or some other kind of proxy that is decoding the gzip stream and returning plain text content to you. You seem to have a lot of extensions installed, which tend to be problematic when debugging issues. Try using a different browser or run in some kind of private mode?
